// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: actions.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const addArtifact = `-- name: AddArtifact :one
INSERT INTO artifacts (id, flow_id, action_id, kind, name, content, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb)
RETURNING id, flow_id, action_id, kind, name, content, metadata, created_at
`

type AddArtifactParams struct {
	ID       string
	FlowID   string
	ActionID string
	Kind     string
	Name     string
	Content  string
	Metadata json.RawMessage
}

func (q *Queries) AddArtifact(ctx context.Context, arg AddArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, addArtifact,
		arg.ID,
		arg.FlowID,
		arg.ActionID,
		arg.Kind,
		arg.Name,
		arg.Content,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ActionID,
		&i.Kind,
		&i.Name,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const completeAction = `-- name: CompleteAction :one
UPDATE actions
SET status = $1, output = $2::jsonb, updated_at = NOW()
WHERE id = $3
RETURNING id, flow_id, task_id, subtask_id, agent_role, function_name, input, output, status, execution_mode, created_at, updated_at
`

type CompleteActionParams struct {
	Status string
	Output json.RawMessage
	ID     string
}

func (q *Queries) CompleteAction(ctx context.Context, arg CompleteActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, completeAction, arg.Status, arg.Output, arg.ID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.AgentRole,
		&i.FunctionName,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeExecution = `-- name: CompleteExecution :exec
UPDATE executions
SET profile = $1,
    runtime = $2,
    metadata = $3::jsonb,
    status = $4,
    completed_at = NOW()
WHERE id = $5
`

type CompleteExecutionParams struct {
	Profile  string
	Runtime  string
	Metadata json.RawMessage
	Status   string
	ID       string
}

func (q *Queries) CompleteExecution(ctx context.Context, arg CompleteExecutionParams) error {
	_, err := q.db.ExecContext(ctx, completeExecution,
		arg.Profile,
		arg.Runtime,
		arg.Metadata,
		arg.Status,
		arg.ID,
	)
	return err
}

const createAction = `-- name: CreateAction :one
INSERT INTO actions (id, flow_id, task_id, subtask_id, agent_role, function_name, input, status, execution_mode)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb,
    $8,
    $9
)
RETURNING id, flow_id, task_id, subtask_id, agent_role, function_name, input, output, status, execution_mode, created_at, updated_at
`

type CreateActionParams struct {
	ID            string
	FlowID        string
	TaskID        string
	SubtaskID     string
	AgentRole     string
	FunctionName  string
	Input         json.RawMessage
	Status        string
	ExecutionMode string
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction,
		arg.ID,
		arg.FlowID,
		arg.TaskID,
		arg.SubtaskID,
		arg.AgentRole,
		arg.FunctionName,
		arg.Input,
		arg.Status,
		arg.ExecutionMode,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.AgentRole,
		&i.FunctionName,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (id, flow_id, action_id, profile, runtime, metadata, status)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7)
RETURNING id, flow_id, action_id, profile, runtime, metadata, status, started_at, completed_at
`

type CreateExecutionParams struct {
	ID       string
	FlowID   string
	ActionID string
	Profile  string
	Runtime  string
	Metadata json.RawMessage
	Status   string
}

type CreateExecutionRow struct {
	ID          string
	FlowID      string
	ActionID    string
	Profile     string
	Runtime     string
	Metadata    json.RawMessage
	Status      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (CreateExecutionRow, error) {
	row := q.db.QueryRowContext(ctx, createExecution,
		arg.ID,
		arg.FlowID,
		arg.ActionID,
		arg.Profile,
		arg.Runtime,
		arg.Metadata,
		arg.Status,
	)
	var i CreateExecutionRow
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ActionID,
		&i.Profile,
		&i.Runtime,
		&i.Metadata,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listActionsByFlow = `-- name: ListActionsByFlow :many
SELECT id, flow_id, task_id, subtask_id, agent_role, function_name, input, output, status, execution_mode, created_at, updated_at
FROM actions
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListActionsByFlow(ctx context.Context, flowID string) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, listActionsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AgentRole,
			&i.FunctionName,
			&i.Input,
			&i.Output,
			&i.Status,
			&i.ExecutionMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByFlow = `-- name: ListArtifactsByFlow :many
SELECT id, flow_id, action_id, kind, name, content, metadata, created_at
FROM artifacts
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsByFlow(ctx context.Context, flowID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.ActionID,
			&i.Kind,
			&i.Name,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByFlow = `-- name: ListExecutionsByFlow :many
SELECT id, flow_id, action_id, profile, runtime, metadata, status, started_at, completed_at
FROM executions
WHERE flow_id = $1
ORDER BY started_at ASC
`

type ListExecutionsByFlowRow struct {
	ID          string
	FlowID      string
	ActionID    string
	Profile     string
	Runtime     string
	Metadata    json.RawMessage
	Status      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

func (q *Queries) ListExecutionsByFlow(ctx context.Context, flowID string) ([]ListExecutionsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionsByFlowRow
	for rows.Next() {
		var i ListExecutionsByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.ActionID,
			&i.Profile,
			&i.Runtime,
			&i.Metadata,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
