// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: agents.sql

package dbgen

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, flow_id, role, model, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, flow_id, role, model, status, created_at, updated_at
`

type CreateAgentParams struct {
	ID     string
	FlowID string
	Role   string
	Model  string
	Status string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.FlowID,
		arg.Role,
		arg.Model,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Role,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByFlow = `-- name: ListAgentsByFlow :many
SELECT id, flow_id, role, model, status, created_at, updated_at
FROM agents
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentsByFlow(ctx context.Context, flowID string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Role,
			&i.Model,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateAgentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.Status, arg.ID)
	return err
}
