// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const listEvents = `-- name: ListEvents :many
SELECT seq, id, flow_id, event_type, message, payload, created_at
FROM events
WHERE flow_id = $1 AND seq > $2
ORDER BY seq ASC
`

type ListEventsParams struct {
	FlowID string
	Seq    int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.FlowID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FlowID,
			&i.EventType,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :one
INSERT INTO events (id, flow_id, event_type, message, payload)
VALUES ($1, $2, $3, $4, $5::jsonb)
RETURNING seq, id, flow_id, event_type, message, payload, created_at
`

type RecordEventParams struct {
	ID        string
	FlowID    string
	EventType string
	Message   string
	Payload   json.RawMessage
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, recordEvent,
		arg.ID,
		arg.FlowID,
		arg.EventType,
		arg.Message,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FlowID,
		&i.EventType,
		&i.Message,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
