// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: findings.sql

package dbgen

import (
	"context"
)

const addFinding = `-- name: AddFinding :one
INSERT INTO findings (id, flow_id, title, severity, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, flow_id, title, severity, description, created_at
`

type AddFindingParams struct {
	ID          string
	FlowID      string
	Title       string
	Severity    string
	Description string
}

func (q *Queries) AddFinding(ctx context.Context, arg AddFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, addFinding,
		arg.ID,
		arg.FlowID,
		arg.Title,
		arg.Severity,
		arg.Description,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Title,
		&i.Severity,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listFindingsByFlow = `-- name: ListFindingsByFlow :many
SELECT id, flow_id, title, severity, description, created_at
FROM findings
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListFindingsByFlow(ctx context.Context, flowID string) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Title,
			&i.Severity,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
