// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flows.sql

package dbgen

import (
	"context"
	"time"
)

const claimNextQueuedFlow = `-- name: ClaimNextQueuedFlow :one
WITH next_flow AS (
    SELECT id
    FROM flows
    WHERE status = 'queued'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE flows AS f
SET status = 'running', updated_at = NOW()
FROM next_flow
WHERE f.id = next_flow.id
RETURNING f.id, f.name, f.target, f.objective, f.status, f.created_at, f.updated_at
`

type ClaimNextQueuedFlowRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ClaimNextQueuedFlow(ctx context.Context) (ClaimNextQueuedFlowRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextQueuedFlow)
	var i ClaimNextQueuedFlowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (id, name, target, objective, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, target, objective, status, created_at, updated_at
`

type CreateFlowParams struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
}

type CreateFlowRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (CreateFlowRow, error) {
	row := q.db.QueryRowContext(ctx, createFlow,
		arg.ID,
		arg.Name,
		arg.Target,
		arg.Objective,
		arg.Status,
	)
	var i CreateFlowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlow = `-- name: GetFlow :one
SELECT id, name, target, objective, status, created_at, updated_at
FROM flows
WHERE id = $1
`

type GetFlowRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetFlow(ctx context.Context, id string) (GetFlowRow, error) {
	row := q.db.QueryRowContext(ctx, getFlow, id)
	var i GetFlowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlows = `-- name: ListFlows :many
SELECT id, name, target, objective, status, created_at, updated_at
FROM flows
ORDER BY created_at DESC
`

type ListFlowsRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListFlows(ctx context.Context) ([]ListFlowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsRow
	for rows.Next() {
		var i ListFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Target,
			&i.Objective,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueFlow = `-- name: QueueFlow :one
UPDATE flows
SET status = 'queued', updated_at = NOW()
WHERE id = $1
RETURNING id, name, target, objective, status, created_at, updated_at
`

type QueueFlowRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) QueueFlow(ctx context.Context, id string) (QueueFlowRow, error) {
	row := q.db.QueryRowContext(ctx, queueFlow, id)
	var i QueueFlowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowStatus = `-- name: UpdateFlowStatus :one
UPDATE flows
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, name, target, objective, status, created_at, updated_at
`

type UpdateFlowStatusParams struct {
	Status string
	ID     string
}

type UpdateFlowStatusRow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateFlowStatus(ctx context.Context, arg UpdateFlowStatusParams) (UpdateFlowStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateFlowStatus, arg.Status, arg.ID)
	var i UpdateFlowStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
