// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: memory.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const addMemory = `-- name: AddMemory :one
INSERT INTO memories (id, flow_id, action_id, kind, content, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
RETURNING id, flow_id, action_id, kind, content, metadata, created_at
`

type AddMemoryParams struct {
	ID       string
	FlowID   string
	ActionID string
	Kind     string
	Content  string
	Metadata json.RawMessage
}

type AddMemoryRow struct {
	ID        string
	FlowID    string
	ActionID  string
	Kind      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) AddMemory(ctx context.Context, arg AddMemoryParams) (AddMemoryRow, error) {
	row := q.db.QueryRowContext(ctx, addMemory,
		arg.ID,
		arg.FlowID,
		arg.ActionID,
		arg.Kind,
		arg.Content,
		arg.Metadata,
	)
	var i AddMemoryRow
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ActionID,
		&i.Kind,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMemoriesByFlow = `-- name: ListMemoriesByFlow :many
SELECT id, flow_id, action_id, kind, content, metadata, created_at
FROM memories
WHERE flow_id = $1
ORDER BY created_at ASC
`

type ListMemoriesByFlowRow struct {
	ID        string
	FlowID    string
	ActionID  string
	Kind      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) ListMemoriesByFlow(ctx context.Context, flowID string) ([]ListMemoriesByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoriesByFlowRow
	for rows.Next() {
		var i ListMemoriesByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.ActionID,
			&i.Kind,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, flow_id, action_id, kind, content, metadata, created_at
FROM memories
WHERE flow_id = $1 AND ($2 = '%%' OR content ILIKE $2)
ORDER BY created_at DESC
`

type SearchMemoriesParams struct {
	FlowID string
	Query  interface{}
}

type SearchMemoriesRow struct {
	ID        string
	FlowID    string
	ActionID  string
	Kind      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]SearchMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemories, arg.FlowID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesRow
	for rows.Next() {
		var i SearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.ActionID,
			&i.Kind,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
