// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Action struct {
	ID            string
	FlowID        string
	TaskID        string
	SubtaskID     string
	AgentRole     string
	FunctionName  string
	Input         json.RawMessage
	Output        json.RawMessage
	Status        string
	ExecutionMode string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Agent struct {
	ID        string
	FlowID    string
	Role      string
	Model     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Approval struct {
	ID          string
	FlowID      string
	TenantID    string
	Kind        string
	Status      string
	RequestedBy string
	ReviewedBy  string
	ReviewNote  string
	Reason      string
	Payload     json.RawMessage
	CreatedAt   time.Time
	ReviewedAt  sql.NullTime
}

type Artifact struct {
	ID        string
	FlowID    string
	ActionID  string
	Kind      string
	Name      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

type Event struct {
	Seq       int64
	ID        string
	FlowID    string
	EventType string
	Message   string
	Payload   json.RawMessage
	CreatedAt time.Time
}

type Execution struct {
	ID          string
	FlowID      string
	ActionID    string
	Profile     string
	Runtime     string
	Status      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
	Metadata    json.RawMessage
}

type Finding struct {
	ID          string
	FlowID      string
	Title       string
	Severity    string
	Description string
	CreatedAt   time.Time
}

type Flow struct {
	ID        string
	Name      string
	Target    string
	Objective string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	TenantID  string
}

type Memory struct {
	ID              string
	FlowID          string
	ActionID        string
	Kind            string
	Content         string
	Metadata        json.RawMessage
	CreatedAt       time.Time
	Embedding       interface{}
	EmbeddingModel  string
	RetentionPolicy string
}

type Subtask struct {
	ID          string
	TaskID      string
	FlowID      string
	Name        string
	Description string
	AgentRole   string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Task struct {
	ID          string
	FlowID      string
	Name        string
	Description string
	AgentRole   string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
