// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package dbgen

import (
	"context"
)

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO subtasks (id, flow_id, task_id, name, description, agent_role, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, flow_id, name, description, agent_role, status, created_at, updated_at
`

type CreateSubtaskParams struct {
	ID          string
	FlowID      string
	TaskID      string
	Name        string
	Description string
	AgentRole   string
	Status      string
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRowContext(ctx, createSubtask,
		arg.ID,
		arg.FlowID,
		arg.TaskID,
		arg.Name,
		arg.Description,
		arg.AgentRole,
		arg.Status,
	)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FlowID,
		&i.Name,
		&i.Description,
		&i.AgentRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, flow_id, name, description, agent_role, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, flow_id, name, description, agent_role, status, created_at, updated_at
`

type CreateTaskParams struct {
	ID          string
	FlowID      string
	Name        string
	Description string
	AgentRole   string
	Status      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.FlowID,
		arg.Name,
		arg.Description,
		arg.AgentRole,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Name,
		&i.Description,
		&i.AgentRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubtasksByFlow = `-- name: ListSubtasksByFlow :many
SELECT id, task_id, flow_id, name, description, agent_role, status, created_at, updated_at
FROM subtasks
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSubtasksByFlow(ctx context.Context, flowID string) ([]Subtask, error) {
	rows, err := q.db.QueryContext(ctx, listSubtasksByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subtask
	for rows.Next() {
		var i Subtask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FlowID,
			&i.Name,
			&i.Description,
			&i.AgentRole,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByFlow = `-- name: ListTasksByFlow :many
SELECT id, flow_id, name, description, agent_role, status, created_at, updated_at
FROM tasks
WHERE flow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTasksByFlow(ctx context.Context, flowID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Name,
			&i.Description,
			&i.AgentRole,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubtaskStatus = `-- name: UpdateSubtaskStatus :exec
UPDATE subtasks
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateSubtaskStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSubtaskStatus(ctx context.Context, arg UpdateSubtaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubtaskStatus, arg.Status, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateTaskStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
